[package]
name = "pterodapter"
version = "0.0.1"
edition = "2021"
authors = ["Dmitry Zolotukhin <zlogic@gmail.com>"]
repository = "https://github.com/zlogic/pterodapter"
license = "Apache-2.0"
rust-version = "1.77"

[dependencies]
log = { version = "0.4", default-features = false }
tokio = { version = "1.38", default-features = false, features = ["rt", "io-util", "signal", "net", "time", "sync"] }
rand = { version = "0.8", default-features = false, features = ["std", "std_rng"] }

sha1 = { version = "0.10", default-features = false, features = ["oid"] }
p256 = { version = "0.13", default-features = false, features = ["arithmetic", "ecdsa"] }
hmac = { version = "0.12", default-features = false, features = ["reset"] }
sha2 = { version = "0.10", default-features = false }
aes = { version = "0.8", default-features = false }
aes-gcm = { version = "0.10", default-features = false, features = ["aes"] }
crypto-bigint = { version = "*", default-features = false, features = ["rand"] }
der = { version = "*", default-features = false }
x509-cert = { version = "*", default-features = false, features = ["pem", "std"] }
rsa = { version = "*", default-features = false, features = ["pem", "std"] }
cipher = { version = "*", default-features = false, features = ["block-padding"] }
cbc = { version = "*", default-features = false }

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
