[package]
name = "pterodapter"
version = "0.0.1"
edition = "2021"
authors = ["Dmitry Zolotukhin <zlogic@gmail.com>"]
repository = "https://github.com/zlogic/pterodapter"
license = "Apache-2.0"
rust-version = "1.77"

[dependencies]
log = { version = "0.4", default-features = false }

async-channel = { version = "2.0", default-features = false }
async-net = { version = "2.0", default-features = false }
async-io = { version = "*", default-features = false }
async-executor = { version = "1.5", default-features = false }
futures-lite = { version = "2.0", default-features = false }

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
