[package]
name = "pterodapter"
version = "0.2.0"
edition = "2021"
authors = ["Dmitry Zolotukhin <zlogic@gmail.com>"]
repository = "https://github.com/zlogic/pterodapter"
license = "Apache-2.0"
rust-version = "1.77"

[dependencies]
log = { version = "0.4", default-features = false }
tokio = { version = "1.39", default-features = false, features = ["rt", "io-util", "signal", "net", "fs", "time", "sync"] }
tokio-rustls = { version = "0.26", default-features = false, features = ["ring"] }
rustls-platform-verifier = { version = "0.3", default-features = false }
rand = { version = "0.8", default-features = false, features = ["std", "std_rng"] }

smoltcp = { version = "0.11", optional = true, default-features = false, features = ["std", "medium-ip", "proto-ipv4", "proto-ipv4-fragmentation", "proto-ipv6", "proto-ipv6-fragmentation", "socket-tcp"] }

ring = { version = "*", optional = true, default-features = false }
webpki = { version = "*", optional = true, default-features = false }
base64 = { version = "*", optional = true, default-features = false, features = ["alloc"] }
x509-parser = { version = "0.16", optional = true, default-features = false, features = ["validate"] }

[features]
default = ["proxy", "ikev2"]
proxy = ["smoltcp"]
ikev2 = ["ring", "webpki", "base64", "x509-parser"]

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
